added register
kshvydkyi/AnonymousWebster pull request #35
Opened 2023-04-26 11:38 UTC by studentprogrammer17

2023-04-26 12:03 UTC, kshvydkyi requested changes

2023-04-26 12:03 UTC, kshvydkyi commented on client/src/components/Auth/Login/Login.jsx
> +}
Login пустий + має бути стрілочна функція

2023-04-27 09:43 UTC, kshvydkyi requested changes

2023-04-27 09:43 UTC, kshvydkyi commented on client/src/components/Auth/Register/Register.jsx
> +                helperText={FULLNAME_REGEX.test(fullName) === false ? 'Full Name is incorrect!' : ' '}
Має бути зрозуміла інструкція для користувача. А то інкорект, а чо воно інкорект, хуй зна. Там треба щось типу: required, 3-24 characters.

2023-04-27 09:43 UTC, kshvydkyi commented on client/src/components/Auth/Register/Register.jsx
> +                helperText={USER_REGEX.test(login) === false ? 'Login is incorrect!' : ' '}
теж саме. Тут має бути зрозуміла інструкція

2023-04-27 09:43 UTC, kshvydkyi commented on client/src/components/Auth/Register/Register.jsx
> +                    helperText={EMAIL_REGEX.test(email) === false ? 'Email is incorrect!' : ' '}
Теж саме, має бути зрозуміла інструкція

2023-04-27 09:43 UTC, kshvydkyi commented on client/src/components/Auth/Register/Register.jsx
> +                    helperText={PWD_REGEX.test(password) === false ? 'Password is incorrect!' : ' '}
Теж саме, має бути зрозуміла інструкція

2023-04-27 09:43 UTC, kshvydkyi commented on client/src/components/Auth/Register/Register.jsx
> +                    helperText={PWD_REGEX.test(confirmPassword) === false ? 'Confirmation Password is incorrect!' : ' '}
Теж саме, має бути зрозуміла інструкція

2023-04-27 09:43 UTC, kshvydkyi commented on client/src/components/Auth/Register/RegisterStyle.jsx
> +    backgroundColor: '#373C3D',
Задній фон: #131313

2023-04-27 09:43 UTC, kshvydkyi commented on client/src/components/Auth/Register/RegisterStyle.jsx
> +    '& .MuiTextField-root': { m: 1, width: '25ch' },
Вказуй тут у відсотках, щоб коли екран зменшується, зменшувались поля. Так краще для адаптивності

2023-04-27 09:44 UTC, kshvydkyi commented on client/src/components/Auth/Register/RegisterStyle.jsx
> +    '& .MuiTextField-root': { m: 1, width: '25ch' },
там де width

2023-04-27 12:38 UTC, kshvydkyi requested changes

2023-04-27 12:38 UTC, kshvydkyi commented on client/src/components/Auth/Header.jsx
> +        </button>
По перше, юзай button з MUI, по друге юзай Material icons: https://mui.com/material-ui/material-icons/

2023-04-27 12:38 UTC, kshvydkyi commented on client/src/components/Auth/Login.jsx
> +            }
У нас більше не приходять на сервері такі помилки. Зроби не по месседжу а по статус коду.

2023-04-27 12:38 UTC, kshvydkyi commented on client/src/components/Auth/Register.jsx
> +    };
теж саме. зроби по статус коду

2023-04-27 12:38 UTC, kshvydkyi commented on client/src/components/Auth/Register.jsx
> +                    helperText={PWD_REGEX.test(confirmPassword) === false && submitClicked === true ? 'Password must be not less than 8 symbols, including: digits, capital letter and at least one spe
Тут має бути helperText "має співпадати з пасвордом/полем вище". Або щось таке

2023-04-27 12:38 UTC, kshvydkyi commented on client/src/styles/RegisterStyle.jsx
>      '& .MuiTextField-root': { m: 1, width: '25ch' },
Width ВКАЖИ У ВІДСОТКАХ

2023-04-27 12:50 UTC, kshvydkyi commented on client/src/components/Other/DialogWIndow.jsx
> +
По перше прибери sx, по друге дроби його темним. Бо в мене він світлий
![image](https://user-images.githubusercontent.com/72373801/234867041-b48212fa-7dba-411e-b74c-51820c88501e.png)

2023-04-27 14:48 UTC, kshvydkyi requested changes

2023-04-27 14:48 UTC, kshvydkyi commented on client/src/components/Auth/Header.jsx
> +        </Button>
Style пропсом. className прибери, якщо ти їх не юзаєш

2023-04-27 14:48 UTC, kshvydkyi commented on client/src/components/Auth/Header.jsx
> +        </Button>
Logout візьми з матеріал айконс. Там можна встановити пакет і з нього імпортувати

2023-04-27 14:48 UTC, kshvydkyi commented on client/src/components/Auth/Header.jsx
> +        <img src={userAvatar && userAvatar !== 'undefined' && userAvatar !== undefined ? `${route.serverURL}/avatars/${userAvatar}` : `${route.serverURL}/avatars/default_avatar.png`} className='link-
Аватар теж саме. Там є в матеріал юай компонент аватар, читай доки

2023-04-27 14:58 UTC, kshvydkyi commented on client/src/components/Auth/Header.jsx
> +        <img src={userAvatar && userAvatar !== 'undefined' && userAvatar !== undefined ? `${route.serverURL}/avatars/${userAvatar}` : `${route.serverURL}/avatars/default_avatar.png`} className='link-
https://mui.com/material-ui/react-avatar/

2023-04-27 14:59 UTC, kshvydkyi commented on client/src/components/Auth/Header.jsx
> +        </Button>
https://mui.com/material-ui/icons/ 

https://mui.com/material-ui/material-icons/

2023-04-28 13:53 UTC, ArtemYo8283 approved these changes

2023-04-28 13:53 UTC, merged