PhotoEditor
kshvydkyi/AnonymousWebster pull request #57
Opened 2023-05-12 10:43 UTC by kshvydkyi

LOL its working

2023-05-13 12:04 UTC, studentprogrammer17 approved these changes
good

2023-05-17 12:14 UTC, ArtemYo8283 commented on server/assets/projects/kossyaak/test/test.json
rgb to rgba

2023-05-17 12:15 UTC, ArtemYo8283 requested changes

2023-05-17 12:15 UTC, ArtemYo8283 commented on server/assets/projects/kossyaak/test/test.json
rgb to rgba

2023-05-17 13:16 UTC, kshvydkyi commented on server/assets/projects/kossyaak/test/test.json
Воно приймає будь який формат. Чек криейт форму. В залежності від того що ти напишеш в колір, воно те і поставить

2023-05-19 15:53 UTC, merged